const APPLICATION_STATUSES = Object.freeze({
  DRAFT: "draft",
  SUBMITTED: "submitted",
  BARANGAY_APPROVED: "barangay_approved",
  BARANGAY_REJECTED: "barangay_rejected",
  APPROVED: "approved",
  REJECTED: "rejected",
  UNDER_REVIEW: "under_review",
  ADDITIONAL_REQUIREMENTS: "additional_requirements",
  RENEWAL: "renewal",
});

const BARANGAY_DECISIONS = Object.freeze({
  APPROVE: "approve",
  REJECT: "reject",
});

const CITY_QUEUE_STATUSES = Object.freeze([
  APPLICATION_STATUSES.BARANGAY_APPROVED,
  APPLICATION_STATUSES.UNDER_REVIEW,
  APPLICATION_STATUSES.ADDITIONAL_REQUIREMENTS,
  APPLICATION_STATUSES.APPROVED,
  APPLICATION_STATUSES.REJECTED,
  APPLICATION_STATUSES.RENEWAL,
]);

module.exports = { APPLICATION_STATUSES, BARANGAY_DECISIONS, CITY_QUEUE_STATUSES };