import { useEffect, useState } from 'react';
import Icon from '../../components/Icon';
import PageHeader from '../../components/PageHeader';
import { api } from '../../lib/api';

type EventRecord = { _id: string; name: string; startsAt: string; endsAt?: string; location: string; required: boolean; attendanceStatus?: string | null };
const date = (value: string) => new Date(value).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
const time = (value: string) => new Date(value).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });

export default function StudentEvents() {
  const [events, setEvents] = useState<EventRecord[]>([]);
  const [error, setError] = useState('');
  const [attending, setAttending] = useState('');
  const load = () => api<{ events: EventRecord[] }>('/events').then(result => setEvents(result.events)).catch(requestError => setError(requestError instanceof Error ? requestError.message : 'Unable to load events.'));
  useEffect(() => { load(); }, []);
  const markAttendance = async (id: string) => { setAttending(id); try { await api(`/events/${id}/attendance`, { method: 'POST' }); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to record attendance.'); } finally { setAttending(''); } };
  const upcoming = events.filter(event => new Date(event.startsAt) >= new Date());
  const completed = events.filter(event => new Date(event.startsAt) < new Date());
  return <div><PageHeader title="Event Attendance" subtitle="Track scholarship events and attendance" breadcrumb={['Student Portal', 'Event Attendance']} />{error && <div className="mb-4 bg-red-50 rounded-xl p-4 text-sm text-red-700">{error}</div>}<div className="grid grid-cols-3 gap-4 mb-6"><div className="bg-white rounded-xl border border-[#E5E7EB] p-4 text-center"><div className="text-2xl font-800 text-[#0B1F3A]">{events.filter(event => event.attendanceStatus === 'attended').length}</div><div className="text-xs text-[#6B7280] mt-1">Attended</div></div><div className="bg-white rounded-xl border border-[#E5E7EB] p-4 text-center"><div className="text-2xl font-800 text-[#D97706]">{upcoming.length}</div><div className="text-xs text-[#6B7280] mt-1">Upcoming</div></div><div className="bg-white rounded-xl border border-[#E5E7EB] p-4 text-center"><div className="text-2xl font-800 text-[#DC2626]">{upcoming.filter(event => event.required).length}</div><div className="text-xs text-[#6B7280] mt-1">Required Remaining</div></div></div><h3 className="font-700 text-sm text-[#1F2937] mb-3">Upcoming Events</h3><div className="space-y-3 mb-6">{upcoming.length === 0 ? <div className="bg-white rounded-2xl border border-[#E5E7EB] p-8 text-center text-sm text-[#6B7280]">No upcoming events.</div> : upcoming.map(event => <div key={event._id} className="bg-white rounded-2xl border border-[#E5E7EB] p-5 flex items-center gap-4"><div className="w-10 h-10 rounded-xl bg-[#0B1F3A] flex items-center justify-center text-white"><Icon name="calendar" size={17} /></div><div className="flex-1"><div className="font-600 text-sm text-[#1F2937]">{event.name} {event.required && <span className="text-xs text-red-600 ml-1">Required</span>}</div><div className="text-xs text-[#6B7280]">{date(event.startsAt)} · {time(event.startsAt)} · {event.location}</div></div></div>)}</div><h3 className="font-700 text-sm text-[#1F2937] mb-3">Attendance History</h3><div className="bg-white rounded-2xl border border-[#E5E7EB] divide-y divide-[#E5E7EB]">{completed.length === 0 ? <div className="p-8 text-center text-sm text-[#6B7280]">No completed events.</div> : completed.map(event => <div key={event._id} className="px-5 py-4 flex items-center gap-4"><Icon name={event.attendanceStatus === 'attended' ? 'check-circle' : 'calendar'} size={17} className={event.attendanceStatus === 'attended' ? 'text-[#22A06B]' : 'text-[#9CA3AF]'} /><div className="flex-1"><div className="font-600 text-sm text-[#1F2937]">{event.name}</div><div className="text-xs text-[#6B7280]">{date(event.startsAt)} · {event.location}</div></div>{event.attendanceStatus === 'attended' ? <span className="text-xs text-[#22A06B]">Attended</span> : <button onClick={() => markAttendance(event._id)} disabled={attending === event._id} className="px-3 py-1.5 bg-[#0B1F3A] text-white rounded-lg text-xs">{attending === event._id ? 'Saving...' : 'Record attendance'}</button>}</div>)}</div></div>;
}
