import { useEffect, useState } from 'react';
import Icon from '../../components/Icon';
import PageHeader from '../../components/PageHeader';
import { api } from '../../lib/api';

type Announcement = { _id: string; category: string; title: string; body: string; publishedAt: string };
type Notification = { _id: string; title: string; message: string; createdAt: string; readAt?: string };
const date = (value: string) => new Date(value).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

export default function StudentAnnouncements() {
  const [tab, setTab] = useState<'announcements' | 'notifications'>('announcements');
  const [announcements, setAnnouncements] = useState<Announcement[]>([]);
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [expanded, setExpanded] = useState<string | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { Promise.all([api<{ announcements: Announcement[] }>('/announcements'), api<{ notifications: Notification[] }>('/notifications')]).then(([announcementResult, notificationResult]) => { setAnnouncements(announcementResult.announcements); setNotifications(notificationResult.notifications); }).catch(requestError => setError(requestError instanceof Error ? requestError.message : 'Unable to load updates.')); }, []);
  return <div><PageHeader title="Announcements & Notifications" subtitle="Updates from the City Scholarship Office" breadcrumb={['Student Portal', 'Announcements']} />{error && <div className="mb-4 bg-red-50 rounded-xl p-4 text-sm text-red-700">{error}</div>}<div className="flex gap-1 mb-5 bg-[#F6F7F9] rounded-xl p-1 w-fit"><button onClick={() => setTab('announcements')} className={`px-4 py-2 rounded-lg text-sm font-600 ${tab === 'announcements' ? 'bg-white shadow-sm text-[#0B1F3A]' : 'text-[#6B7280]'}`}>Announcements</button><button onClick={() => setTab('notifications')} className={`px-4 py-2 rounded-lg text-sm font-600 ${tab === 'notifications' ? 'bg-white shadow-sm text-[#0B1F3A]' : 'text-[#6B7280]'}`}>Notifications ({notifications.filter(notification => !notification.readAt).length})</button></div>{tab === 'announcements' ? <div className="space-y-4">{announcements.length === 0 ? <div className="bg-white rounded-2xl border border-[#E5E7EB] p-10 text-center text-sm text-[#6B7280]">No announcements have been published.</div> : announcements.map(announcement => <div key={announcement._id} className="bg-white rounded-2xl border border-[#E5E7EB] overflow-hidden"><button onClick={() => setExpanded(expanded === announcement._id ? null : announcement._id)} className="w-full text-left px-5 py-4"><div className="flex items-center gap-2 mb-1"><span className="px-2 py-0.5 bg-[#0B1F3A]/5 text-[#163A63] text-xs font-600 rounded-md">{announcement.category}</span><span className="text-xs text-[#9CA3AF]">{date(announcement.publishedAt)}</span></div><div className="font-600 text-sm text-[#1F2937]">{announcement.title}</div></button>{expanded === announcement._id && <div className="px-5 pb-4 border-t border-[#E5E7EB] pt-4 text-sm text-[#6B7280]">{announcement.body}</div>}</div>)}</div> : <div className="bg-white rounded-2xl border border-[#E5E7EB] divide-y divide-[#E5E7EB]">{notifications.length === 0 ? <div className="p-10 text-center text-sm text-[#6B7280]">No notifications yet.</div> : notifications.map(notification => <div key={notification._id} className="px-5 py-4 flex items-start gap-3"><Icon name="bell" size={16} className="text-[#2563EB] mt-1" /><div><div className="text-sm font-600 text-[#1F2937]">{notification.title}</div><div className="text-xs text-[#6B7280] mt-1">{notification.message}</div><div className="text-xs text-[#9CA3AF] mt-1">{date(notification.createdAt)}</div></div></div>)}</div>}</div>;
}
