import { useEffect, useState } from 'react';
import PageHeader from '../../components/PageHeader';
import { api } from '../../lib/api';

type Announcement = { _id: string; category: string; title: string; body: string; publishedAt: string };
const date = (value: string) => new Date(value).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

export default function CityAnnouncements() {
  const [announcements, setAnnouncements] = useState<Announcement[]>([]); const [form, setForm] = useState({ category: 'General', title: '', body: '' }); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = () => api<{ announcements: Announcement[] }>('/announcements').then(result => setAnnouncements(result.announcements)).catch(requestError => setError(requestError instanceof Error ? requestError.message : 'Unable to load announcements.'));
  useEffect(() => { load().finally(() => setLoading(false)); }, []);
  const publish = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await api('/announcements', { method: 'POST', body: JSON.stringify(form) }); setForm({ category: 'General', title: '', body: '' }); setOpen(false); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to publish announcement.'); } finally { setSaving(false); } };
  if (loading) return <div className="py-16 text-center text-sm text-[#6B7280]">Loading announcements...</div>;
  return <div><PageHeader title="Announcements" subtitle="Publish updates visible to students and barangay staff" breadcrumb={['City Office', 'Announcements']} action={<button onClick={() => setOpen(true)} className="px-4 py-2 rounded-xl bg-[#0B1F3A] text-white text-sm font-700">Publish Announcement</button>} />{error && <div className="mb-4 bg-red-50 rounded-xl p-4 text-sm text-red-700">{error}</div>}<div className="space-y-4">{announcements.length === 0 ? <div className="bg-white rounded-2xl border border-[#E5E7EB] p-10 text-center text-sm text-[#6B7280]">No announcements published yet.</div> : announcements.map(announcement => <article key={announcement._id} className="bg-white rounded-2xl border border-[#E5E7EB] p-5"><div className="flex items-center gap-2 mb-2"><span className="px-2 py-0.5 bg-[#0B1F3A]/5 text-[#163A63] text-xs font-600 rounded-md">{announcement.category}</span><span className="text-xs text-[#9CA3AF]">{date(announcement.publishedAt)}</span></div><h2 className="font-700 text-sm text-[#1F2937]">{announcement.title}</h2><p className="text-sm text-[#6B7280] mt-2 leading-relaxed">{announcement.body}</p></article>)}</div>{open && <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40"><form onSubmit={publish} className="bg-white rounded-2xl shadow-2xl w-full max-w-lg p-6 space-y-4"><div className="flex justify-between"><h2 className="font-700 text-[#1F2937]">Publish Announcement</h2><button type="button" onClick={() => setOpen(false)}>×</button></div><input required value={form.category} onChange={event => setForm({ ...form, category: event.target.value })} className="w-full px-3 py-2.5 border border-[#E5E7EB] rounded-xl text-sm" placeholder="Category" /><input required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} className="w-full px-3 py-2.5 border border-[#E5E7EB] rounded-xl text-sm" placeholder="Title" /><textarea required value={form.body} onChange={event => setForm({ ...form, body: event.target.value })} className="w-full px-3 py-2.5 border border-[#E5E7EB] rounded-xl text-sm" rows={5} placeholder="Announcement details" /><button disabled={saving} className="w-full py-2.5 rounded-xl bg-[#0B1F3A] text-white text-sm font-700">{saving ? 'Publishing...' : 'Publish'}</button></form></div>}</div>;
}
