import { useEffect, useState } from 'react';
import PageHeader from '../../components/PageHeader';
import StatCard from '../../components/StatCard';
import { api } from '../../lib/api';

type Application = { _id: string; status: string; school: string; createdAt: string };
type DocumentRecord = { _id: string; status: string };
export default function CityReports() {
  const [applications, setApplications] = useState<Application[]>([]); const [documents, setDocuments] = useState<DocumentRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api<{ applications: Application[] }>('/applications'), api<{ documents: DocumentRecord[] }>('/documents')]).then(([applicationResult, documentResult]) => { setApplications(applicationResult.applications); setDocuments(documentResult.documents); }).catch(requestError => setError(requestError instanceof Error ? requestError.message : 'Unable to load report data.')).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="py-16 text-center text-sm text-[#6B7280]">Generating live report...</div>;
  const approved = applications.filter(application => application.status === 'approved').length; const rejected = applications.filter(application => application.status === 'rejected').length; const schools = [...new Set(applications.map(application => application.school))];
  return <div><PageHeader title="Reports" subtitle="Live summaries generated from student submissions" breadcrumb={['City Office', 'Reports']} />{error && <div className="mb-4 bg-red-50 rounded-xl p-4 text-sm text-red-700">{error}</div>}<div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-5"><StatCard label="Total Applications" value={String(applications.length)} icon="clipboard" change="Live database total" changeType="neutral" /><StatCard label="Approved" value={String(approved)} icon="check-circle" change="Application status" changeType="neutral" /><StatCard label="Rejected" value={String(rejected)} icon="x-circle" change="Application status" changeType="neutral" /><StatCard label="Documents" value={String(documents.length)} icon="file-text" change="Student uploads" changeType="neutral" /></div><div className="bg-white rounded-2xl border border-[#E5E7EB] overflow-hidden"><div className="px-5 py-4 border-b border-[#E5E7EB]"><h2 className="font-600 text-sm text-[#1F2937]">Applications by school</h2></div>{schools.length === 0 ? <div className="p-10 text-center text-sm text-[#6B7280]">No application data available.</div> : <div className="divide-y divide-[#E5E7EB]">{schools.map(school => { const count = applications.filter(application => application.school === school).length; return <div key={school} className="px-5 py-4 flex items-center gap-4"><div className="flex-1 text-sm text-[#1F2937]">{school}</div><div className="w-40 h-2 bg-[#F6F7F9] rounded-full"><div className="h-full bg-[#163A63] rounded-full" style={{ width: `${count / applications.length * 100}%` }} /></div><div className="w-8 text-right text-sm font-600">{count}</div></div>; })}</div>}</div></div>;
}
