import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import Icon from '../../components/Icon';
import StatusBadge from '../../components/StatusBadge';
import PageHeader from '../../components/PageHeader';
import { api } from '../../lib/api';

type Application = { _id: string; student?: { name: string; email: string }; barangay?: { name: string }; program: string; school: string; status: string; createdAt: string; submittedAt?: string };
const date = (value: string) => new Date(value).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

export default function CityApplications() {
  const [applications, setApplications] = useState<Application[]>([]);
  const [filter, setFilter] = useState('all');
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { api<{ applications: Application[] }>('/applications').then(result => setApplications(result.applications)).catch(requestError => setError(requestError instanceof Error ? requestError.message : 'Unable to load applications.')).finally(() => setLoading(false)); }, []);
  const filtered = applications.filter(application => { const name = application.student?.name || ''; const barangay = application.barangay?.name || ''; const matchesSearch = `${name} ${barangay} ${application.school}`.toLowerCase().includes(search.toLowerCase()); return matchesSearch && (filter === 'all' || application.status === filter); });
  const statusTabs = ['all', 'submitted', 'under_review', 'approved', 'rejected'];
  if (loading) return <div className="py-16 text-center text-sm text-[#6B7280]">Loading applications...</div>;
  return <div><PageHeader title="Applications" subtitle="Review applications submitted by students" breadcrumb={['City Office', 'Applications']} />{error && <div className="mb-4 bg-red-50 rounded-xl p-4 text-sm text-red-700">{error}</div>}<div className="flex gap-2 overflow-x-auto pb-1 mb-5">{statusTabs.map(tab => <button key={tab} onClick={() => setFilter(tab)} className={`px-3 py-2 rounded-xl text-xs font-600 whitespace-nowrap border ${filter === tab ? 'bg-[#0B1F3A] text-white border-[#0B1F3A]' : 'bg-white text-[#6B7280] border-[#E5E7EB]'}`}>{tab === 'all' ? 'All' : tab.replace('_', ' ')} <span className="ml-1">{tab === 'all' ? applications.length : applications.filter(application => application.status === tab).length}</span></button>)}</div><div className="relative mb-4"><Icon name="search" size={14} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#9CA3AF]" /><input value={search} onChange={event => setSearch(event.target.value)} className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-[#E5E7EB] text-sm bg-white" placeholder="Search by student, school, or barangay..." /></div><div className="bg-white rounded-2xl border border-[#E5E7EB] overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-[#E5E7EB] bg-[#F6F7F9]">{['Applicant', 'Program / School', 'Barangay', 'Date Submitted', 'Status', 'Actions'].map(header => <th key={header} className="px-5 py-3 text-left text-xs font-600 text-[#6B7280]">{header}</th>)}</tr></thead><tbody className="divide-y divide-[#E5E7EB]">{filtered.map(application => <tr key={application._id} className="hover:bg-[#F6F7F9]"><td className="px-5 py-3.5"><div className="font-600 text-sm text-[#1F2937]">{application.student?.name || 'Unknown student'}</div><div className="text-xs text-[#6B7280]">{application.student?.email}</div></td><td className="px-5 py-3.5 text-sm text-[#6B7280]">{application.program}<div className="text-xs text-[#9CA3AF]">{application.school}</div></td><td className="px-5 py-3.5 text-sm text-[#6B7280]">{application.barangay?.name || 'Not provided'}</td><td className="px-5 py-3.5 text-sm text-[#6B7280]">{date(application.submittedAt || application.createdAt)}</td><td className="px-5 py-3.5"><StatusBadge status={application.status.replace('_', '-')} size="sm" /></td><td className="px-5 py-3.5"><Link to={`/city/applications/${application._id}`} className="inline-flex items-center gap-1 px-3 py-1.5 border border-[#E5E7EB] text-xs font-600 text-[#6B7280] rounded-lg"><Icon name="eye" size={12} /> Review</Link></td></tr>)}</tbody></table></div>{filtered.length === 0 && <div className="p-10 text-center text-sm text-[#6B7280]">No student applications match this view.</div>}<div className="px-5 py-3 border-t border-[#E5E7EB] text-xs text-[#6B7280]">Showing {filtered.length} of {applications.length} applications</div></div></div>;
}
